### ISSUE TITLE
ReferenceError | forge is not defined

### ISSUE THREAD

**Issue by gunjank** [loveiset/RSAForPostman#2]
Where you are getting forge object in given example. Below line always says forge is undefined.

forge.pki.publicKeyFromPem

Error : Error running scripts: ReferenceError | forge is not defined

**Comment by loveiset** [comment]
@gunjank I recheck the example, it worked perfectly. Make sure you do the following:
My Postman version is 6.5.2
1. clear variable `pm.globals.unset("forgeJS");`
2. paste my example into pre-request script section
3. do a get request(for example, www.google.com), with this pre-request **twice**
4. in postman console, you can see the result output

**Comment by Mrpaoletto** [comment]
Hi there, I'm facing this issue as well. Is there any suggestion? I've imported the file forge.js in postman enviroment and ati the beginning of pre-request Script this eval( pm.globals.get('forgeJS')). I'm running on Postman v9.1.2. 
Thank you in advice

**Comment by loveiset** [comment]
> Hi there, I'm facing this issue as well. Is there any suggestion? I've imported the file forge.js in postman enviroment and ati the beginning of pre-request Script this eval( pm.globals.get('forgeJS')). I'm running on Postman v9.1.2. Thank you in advice

I've tried it on Postman v9.09, all worked fine. How do you import it? You can try following script
```javascript
if (!pm.globals.has("forgeJS")) {
    pm.sendRequest("https://raw.githubusercontent.com/loveiset/RSAForPostman/master/forge.js", function (err, res) {
        if (err) {
            console.log(err);
        } else {
            pm.globals.set("forgeJS", res.text());
        }
    })
} else {
eval(postman.getGlobalVariable("forgeJS"));
//you encrypt script here
}
```

**Comment by Mrpaoletto** [comment]
`if (!pm.globals.has("forgeJS")) {
    pm.sendRequest("https://raw.githubusercontent.com/loveiset/RSAForPostman/master/forge.js", function (err, res) {
        if (err) {
            console.log(err);
        } else {
            pm.globals.set("forgeJS", res.text());
        }
    })
} else {
eval(postman.getGlobalVariable("forgeJS"));
var public_key = pm.environment.get('public_key')
var pem = '-----BEGIN PUBLIC KEY----- ' + public_key + '-----END PUBLIC KEY-----';

var usernameToEncrypt = 'IC094404081';
var pinToEncrypt = '123456Aa';

var publicKey = forge.pki.publicKeyFromPem(pem);

var bufferUsername = forge.util.createBuffer(usernameToEncrypt, 'utf8');
var bytesUsername = buffer.getBytes();


var bufferPin = forge.util.createBuffer(pinToEncrypt, 'utf8');
var bytesPin = buffer.getBytes();

var encryptedUsername = publicKey.encrypt(bytesUsername, 'RSA-OAEP', {
            md: forge.md.sha256.create(),
            mgf1: { md: forge.md.sha1.create() }
        });

var encryptedPin = publicKey.encrypt(bytesPin, 'RSA-OAEP', {
            md: forge.md.sha256.create(),
            mgf1: { md: forge.md.sha1.create() }
        });



pm.environment.set("username", encryptedUsername);
pm.environment.set("pin",encryptedPin);
}
`
this is the snippet of code im trying to use, but now it says "buffer not defined"

**Comment by loveiset** [comment]
> `if (!pm.globals.has("forgeJS")) { pm.sendRequest("https://raw.githubusercontent.com/loveiset/RSAForPostman/master/forge.js", function (err, res) { if (err) { console.log(err); } else { pm.globals.set("forgeJS", res.text()); } }) } else { eval(postman.getGlobalVariable("forgeJS")); var public_key = pm.environment.get('public_key') var pem = '-----BEGIN PUBLIC KEY----- ' + public_key + '-----END PUBLIC KEY-----';
> 
> var usernameToEncrypt = 'IC094404081'; var pinToEncrypt = '123456Aa';
> 
> var publicKey = forge.pki.publicKeyFromPem(pem);
> 
> var bufferUsername = forge.util.createBuffer(usernameToEncrypt, 'utf8'); var bytesUsername = buffer.getBytes();
> 
> var bufferPin = forge.util.createBuffer(pinToEncrypt, 'utf8'); var bytesPin = buffer.getBytes();
> 
> var encryptedUsername = publicKey.encrypt(bytesUsername, 'RSA-OAEP', { md: forge.md.sha256.create(), mgf1: { md: forge.md.sha1.create() } });
> 
> var encryptedPin = publicKey.encrypt(bytesPin, 'RSA-OAEP', { md: forge.md.sha256.create(), mgf1: { md: forge.md.sha1.create() } });
> 
> pm.environment.set("username", encryptedUsername); pm.environment.set("pin",encryptedPin); } ` this is the snippet of code im trying to use, but now it says "buffer not defined"

Maybe it's due to your wrong usage of RSA, you can get usage from forge: https://github.com/digitalbazaar/forge
